// 导入模板文件中的所有功能
#import "../template.typ": bi-i, setup, title-date

// 使用 #show 规则将 `setup` 函数应用到整个文档
#show: doc => setup(doc, 2)

// ================================================================
//                       下为正文内容
// ================================================================

// 1. 设置标题日期
#title-date("20251108")

// 2. 使用编号列表 (+) 和 bi-i 函数添加条目
+ #bi-i("the first amateur match in China to attract over 61000 fans\n", "中国第一场吸引超过61000名球迷的业余比赛")
+ #bi-i("depend on/be based on", "依赖于")
+ #bi-i("This large-scale,objective data", "这些大规模的客观数据")
+ #bi-i("match today's best text translators", "匹配当今最好的文本翻译器")
+ #bi-i("even proficient speakers will ...", "即使是熟练的演讲者也会...")
+ #bi-i("equal the beauty and creativity", "等同于美丽和创造力")
+ #bi-i("capture the natural of a conversation", "捕捉对话的自然之处")
+ #bi-i("foreign language signals your willingness to step into ...\n", "外语标志着你愿意步入...")
+ #bi-i("It is engineered to capture clicks", "它被设计用来吸引点击")
+ #bi-i("integrity or the posts", "帖子的完整性")
+ #bi-i("become overly attached to", "变得过度依赖")
+ #bi-i("Reason vs. Desire", "理智与欲望")
+ #bi-i("the pull of", "……的拉力")
+ #bi-i("than vague intentions", "而不是模糊的意图")
+ #bi-i("an implementation intention", "一个执行意图")
+ #bi-i("reframe as", "重塑为")
+ #bi-i("support the green development of the city", "为城市的绿色发展提供动力")
+ #bi-i("lights dim", "灯光渐暗")
+ #bi-i("contemporary documentaries of youth", "现代代青年纪录片")
+ #bi-i("frequent volcanic eruptions", "频繁的火山喷发")
+ #bi-i("layers of ash from ... that be deposited", "来自……的火山灰层被沉积下来")
+ #bi-i("shuttle missions", "航天飞机任务")
+ #bi-i("hard-charging venture", "冲锋陷阵的冒险")
+ #bi-i("whose ultimate goal is", "其最终目标是")
+ #bi-i("towering pad of concrete and steel", "高耸的混凝土和钢铁平台")
+ #bi-i("enhance its status as a leader", "提升其作为领导者的地位")
+ #bi-i("revolutionize an industry", "彻底改变一个行业")
+ #bi-i("recover several of its boosters", "回收其几个助推器")
+ #bi-i("seasoned researcher", "经验丰富的研究员")
+ #bi-i("study", "研究")
+ #bi-i("sound enough", "听起来足够")
+ #bi-i("intensity of the smiles in the images", "图像中微笑的强度")
+ #bi-i("corelation between life span and smile intensity", "寿命与微笑强度之间的关系")
+ #bi-i("A cautionary tale then, of ...", "一个警示故事，关于...")
+ #bi-i("threaten with disease and decline", "以疾病和衰退相威胁")
+ #bi-i("fueled by a warming climate", "由气候变暖推动")
+ #bi-i("activity intensifies", "活动加剧")
+ #bi-i("broad and fundamental changes", "广泛而根本的变化")
+ #bi-i("repopulate", "重新填充")
+ #bi-i("remote villages with ...", "偏远的村庄与...")
+ #bi-i("only by handfuls of people in ...", "只有少数人在...")
+ #bi-i("struggle with an unemployment rate of ...", "与...的失业率作斗争")
+ #bi-i("cannot be overstated", "再强调也不为过")
+ #bi-i("their consumption habit", "他们的消费习惯")
+ #bi-i("joining this initiative", "加入这项倡议")
+ #bi-i("using unconventional materials", "使用非传统材料")
+ #bi-i("solidified his reputation", "巩固了他的声誉")
+ #bi-i("commercial and instantly recognizable", "商业化且易于识别")
+ #bi-i("law enforcement", "执法")
+ #bi-i("several important trials", "几次重要的审判")
+ #bi-i("a must-seen", "必看的")
+ #bi-i("reclaim older terms", "重新使用旧术语")
+ #bi-i("whose strength outweigh that of a dog", "其力量超过了狗")
+ #bi-i("as a shelter for", "作为……的庇护所")
+ #bi-i("trace the county's development", "追溯该县的发展")
+ #bi-i("evoke the sit-in", "唤起静坐")
+ #bi-i("a political memorabilia", "一件政治纪念品")
+ #bi-i("slow hand clap is a great compliment", "缓慢的鼓掌是一种极大的赞美")
+ #bi-i("none other than", "不是别人，正是")
+ #bi-i("no more than", "不超过")
+ #bi-i("don't complement each other", "互不补充")
+ #bi-i("imperfections", "瑕疵")
+ #bi-i("be revoked with", "被……撤销")
+ #bi-i("in the scheme of human events", "在人类事件的宏伟计划中")
+ #bi-i("so rigid that", "如此僵硬以至于")
+ #bi-i("prepare sb. to meet obstacle and prejudices", "让某人准备好迎接障碍和偏见")
+ #bi-i("progress is unalterable", "进步是不可改变的")
+ #bi-i("nothing static with", "没有什么是静止的")
+ #bi-i("stop the human tide from flowing", "阻止人潮涌动")
+ #bi-i("in every walk of life", "在各行各业")
+ #bi-i("in spite of any handicap", "尽管有任何障碍")
+ #bi-i("what I was able to attain", "我所能达到的")
+ #bi-i("soak the place in", "把地方浸泡在")
+ #bi-i("embrace the prospect of being a tourist", "拥抱成为游客的前景")
+ #bi-i("be completely silent", "鸭雀无声")
+ #bi-i("burst into laughter", "大笑了起来")
+ #bi-i("what worth mentioning is that", "值得一提的是")
+ #bi-i("by the time", "到...的时候")
+ #bi-i("establish close relationships with each other", "与用户建立密切关系")
+ #bi-i("enhance users' well-being", "提升用户的幸福感")

