+ #bi-i("the first amateur match in China to attract over 61000 fans", "")
+ #bi-i("depend on=be based on", "")
+ #bi-i("This large-scale,objective data", "")
+ #bi-i("match today's best text translators", "")
+ #bi-i("even proficient speakers will ...", "")
+ #bi-i("equal the beauty and creativity", "")
+ #bi-i("capture the natural of a conversation", "")
+ #bi-i("foreign language signals your willingness to step into ...", "")
+ #bi-i("It is engineered to capture clicks", "")
+ #bi-i("integrity or the posts", "")
+ #bi-i("become overly attached to", "")
+ #bi-i("Reason vs. Desire", "")
+ #bi-i("the pull of", "")
+ #bi-i("than vague intentions", "")
+ #bi-i("an implementation intention", "")
+ #bi-i("reframe as", "")
+ #bi-i("", "为城市的绿色发展提供动力")
+ #bi-i("lights dim", "灯光渐暗")
+ #bi-i("", "百代青年纪录片")
+ #bi-i("frequent volcanic eruptions", "")
+ #bi-i("layers of ash from ... that be deposited", "")
+ #bi-i("shuttle missions", "")
+ #bi-i("hard-charging venture", "")
+ #bi-i("whose ultimate goal is", "")
+ #bi-i("towering pad of concrete and steel", "")
+ #bi-i("enhance its status as a leader", "")
+ #bi-i("revolutionize an industry", "")
+ #bi-i("recover several of its boosters", "")
+ #bi-i("seasoned researcher", "")
+ #bi-i("study", "")
+ #bi-i("sound enough", "")
+ #bi-i("intensity of the smiles in the images", "")
+ #bi-i("corelation between life span and smile intensity", "")
+ #bi-i("A cautionary tale then, of ...", "")
+ #bi-i("threaten with disease and decline", "")
+ #bi-i("fueled by a warming climate", "")
+ #bi-i("activity intensifies", "")
+ #bi-i("broad and fundamental changes", "")
+ #bi-i("repopulate", "")
+ #bi-i("remote villages with ...", "")
+ #bi-i("only by handfuls of people in ...", "")
+ #bi-i("struggle with an unemployment rate of ...", "")
+ #bi-i("cannot be overstated", "再强调也不为过")
+ #bi-i("their consumption habit", "")
+ #bi-i("joining this initiative", "")
+ #bi-i("using unconventional materials", "")
+ #bi-i("solidified his reputation", "")
+ #bi-i("commercial and instantly recognizable", "")
+ #bi-i("law enforcement", "")
+ #bi-i("several important trials", "")
+ #bi-i("a must-seen", "")
+ #bi-i("reclaim older terms", "")
+ #bi-i("whose strength outweigh that of a dog", "")
+ #bi-i("as a shelter for", "")
+ #bi-i("trace the county's development", "")
+ #bi-i("evoke the sit-in", "")
+ #bi-i("a political memorabilia", "")
+ #bi-i("slow hand clap is a great compliment", "")
+ #bi-i("none other than", "")
+ #bi-i("no more than", "")
+ #bi-i("don't complement each other", "")
+ #bi-i("imperfections", "")
+ #bi-i("be revoked with", "")
+ #bi-i("in the scheme of human events", "")
+ #bi-i("so rigid that", "")
+ #bi-i("prepare sb. to meet obstacle and prejudices", "")
+ #bi-i("progress is unalterable", "")
+ #bi-i("nothing static with", "")
+ #bi-i("stop the human tide from flowing", "")
+ #bi-i("in every walk of life", "")
+ #bi-i("in spite of any handicap", "")
+ #bi-i("what I was able to attain", "")
+ #bi-i("soak the place in", "")
+ #bi-i("embrace the prospect of being a tourist", "")
+ #bi-i("be completely silent", "鸭雀无声")
+ #bi-i("burst into laughter", "大笑了起来")
+ #bi-i("what worth mentioning is that", "值得一提的是")
+ #bi-i("by the time", "到...的时候")
+ #bi-i("establish close relationships with each other", "与用户建立密切关系")
+ #bi-i("enhance users' well-being", "提升用户的幸福感")

