+ #bi-i("fulfill this wish", "这里输入中文翻译")
+ #bi-i("restrict A to B", "")
+ #bi-i("Lack of sleep may result in health problems.", "")
+ #bi-i("A result from B", "")
+ #bi-i("as a result of our joint efforts", "")
+ #bi-i("in return for his help", "")
+ #bi-i("the reverse of mine", "")
+ #bi-i("was rewarded with a cash bonus", "")
+ #bi-i("get rid of these nuclear waste", "")
+ #bi-i("be ripe for", "")
+ #bi-i("run the risk of doing", "")
+ #bi-i("at the risk of being fired", "")
+ #bi-i("play an effective role in", "")
+ #bi-i("be rooted in", "")
+ #bi-i("expectations of the future", "")
+ #bi-i("rule out the possibility of", "")
+ #bi-i("be frightened to death", "")
+ #bi-i("sacrifice A for B", "")
+ #bi-i("as prosperous as it used to be.", "")
+ #bi-i("for the sake of", "")
+ #bi-i("be worth promoting on a large scale", "")
+ #bi-i("Scarcely +过完 ... when +过去", "")
+ #bi-i("be scheduled to do", "")
+ #bi-i("scold A for B", "")
+ #bi-i("in search of a decent job", "")
+ #bi-i("out of season", "")
+ #bi-i("in season", "")
+ #bi-i("be seated in/at", "")
+ #bi-i("be second to none", "")
