+ #bi-i("cause a bloom", "")
+ #bi-i("unforeseen side effect", "")
+ #bi-i("a prejudice against geoengineering experiments", "")
+ #bi-i(" hit the headlines", "")
+ #bi-i("a health hazard", "")
+ #bi-i("In an emergency ward", "")
+ #bi-i("pay the tuition for", "")
+ #bi-i("restlessness", "")
+ #bi-i("in case I am tempted to do", "")
+ #bi-i("silence phone's distraction", "")
+ #bi-i("have trouble doing", "")
+ #bi-i("resisting the constant urge to impulse-buy", "")
+ #bi-i("lay the challenges bare", "")
+ #bi-i("subscription payments", "")
+ #bi-i("due date", "")
+ #bi-i("seem justified", "")
+ #bi-i("be in the making", "")
+ #bi-i("reverse our burnout", "")
+ #bi-i("unresolved emotions", "")
+ #bi-i("indignity", "")
+ #bi-i("capacity to move", "")
+ #bi-i("misconception", "")
+ #bi-i("a flattened representation of its territory", "")
+ #bi-i("draw on biased training data", "")
+ #bi-i("the disturbing thing", "")
+ #bi-i("human feedback process", "")
+ #bi-i("bleed into global culture", "")
+ #bi-i("unwittingly adopting", "")
+ #bi-i("neutral tools", "")
+ #bi-i("subtly reshape our thinking", "")
+ #bi-i("engage with digital media", "")
+ #bi-i("age-related changes in cognition", "")
+ #bi-i("adjustments to instructional videos to optimize learning", "")
+ #bi-i("trigger fierce debate online", "")
+ #bi-i("suspension to reading aloud", "")
+ #bi-i("There's no possibility that ...", "不可能...")
+ #bi-i("herb", "草药")
+ #bi-i("handkerchief", "手帕")
+ #bi-i("capture the unique beauty", "捕捉到了独特之美")
+ #bi-i("rural landscape", "乡村景致")
+ #bi-i("traditional festival at Chinese nation", "中华民族传统节日")
+ #bi-i("correspond to", "映射")
+ #bi-i("deep-seated longing for", "骨子里的渴望")
+ #bi-i("reunion and harvest", "团圆与丰收")
+ #bi-i("give through centuries of ups and downs", "历经数百年风雨")
+ #bi-i("serve as a silence witness to sth.", "对...的无声见证者")
