// 导入模板文件中的所有功能
#import "../template.typ": bi-i, setup, title-date

// 使用 #show 规则将 `setup` 函数应用到整个文档
#show: doc => setup(doc, 1)

// ================================================================
//                       下为正文内容
// ================================================================

// 1. 设置标题日期
#title-date("20251116")

// 2. 使用编号列表 (+) 和 bi-i 函数添加条目
+ #bi-i("It's better to be safe than sorry", "小心驶得万年船")
+ #bi-i("catch sb. off guard", "使某人措手不及")
+ #bi-i("New Year's Day this year", "今年元旦")
+ #bi-i("congratulate me on my 18th birthday", "祝贺我18岁生日")
+ #bi-i("after years of constructi", "经过多年的建设")
+ #bi-i("one in his fifties", "五十多岁的人")
+ #bi-i("distinct spices", "已灭绝物种")
+ #bi-i("make up one's mind to join the wildlife conservation organization\n", "立志加入野生动物保护组织")
+ #bi-i("What life you will live in the future is up to you.", "将来过怎样的生活取决于你自己。")
+ #bi-i("turn many people into being crazy about shopping", "不少人变成购物狂")
+ #bi-i("vivid and bright colors", "鲜艳明亮的色彩")
+ #bi-i("What make the game unique is that ...", "这个游戏的独特之处在于")
+ #bi-i("have a comprehensive and accurate knowledge of your ability\n", "对你的能力有全面、准确的了解")
+ #bi-i("make it a practice to write thank-you notes", "养成写感谢信的习惯")
+ #bi-i("a promising fix to mental distress", "缓解精神困扰的有效方法")
+ #bi-i("in the face of what's cloudy, new or unexpected", "面对模糊、新鲜或意外的事物")
+ #bi-i("pathway to building toughness", "培养韧性的途径")
+ #bi-i("mismatch between what we assumed", "与我们的假设不符")
+ #bi-i("update our perception of the world", "更新我们对世界的认知")
+ #bi-i("originate the term", "创造这个术语")
+ #bi-i("blooms are a blooming bussiness", "鲜花是蓬勃发展的生意")
+ #bi-i("an emerging market", "新兴市场")
+ #bi-i("intensify the industry's environment footprint", "加剧该行业的环境足迹")
+ #bi-i("on top of pollutants and water use ", "除了污染物和用水之外")
+ #bi-i("generate serious carbon emissions", "产生严重的碳排放")
+ #bi-i("be roughly equivalent to", "大致相当于")
+ #bi-i("busy streets and towering high-rises", "繁忙的街道和高耸的高楼")
+ #bi-i("decode local idioms", "解读当地习语")
+ #bi-i("convert A to B", "将A转换为B")
+ #bi-i("be carefully complied", "精心编写的")
+ #bi-i("fitness manual", "健身手册")
+ #bi-i("can't help marveling at sth.", "喷啧称奇")
+ #bi-i("tailor ... to specific needs", "对症下药")
+ #bi-i("presales are so popular that even a single ticket is unavailable\n", "预售火爆，一票难求")
+ #bi-i("unevenly distributed weight", "分布不均的重量")
+ #bi-i("urban landscape", "城市景观")
+ #bi-i("fuel the imaginations of", "激发……的想象力")
+ #bi-i("using ... of musicians can be exploitive", "使用音乐家的……可能具有剥削性")
+ #bi-i("scarcity of original video footage", "原始视频素材的稀缺")
+ #bi-i("behave with integrity", "行为正直;诚信行事")
+ #bi-i("territorial integrity", "领土完整")
+ #bi-i("be loaded with many features", "具备许多功能")
+ #bi-i("optimism is justified", "乐观是有道理的")
+ #bi-i("donation from the public", "社会公众的捐赠")
+ #bi-i("gain recognitions", "受到认可")
+ #bi-i("things seemed good", "“听上去很美”的东西")
+ #bi-i("the association helps the young talents", "这个协会扶持青年才俊")
+ #bi-i("anthropologists", "人类学家")
+ #bi-i("proved controversial", "证明有争议")
+ #bi-i("B be frequently owed to A", "B常常归功于A")
+ #bi-i("in various literature forms", "以各种文学形式")
+ #bi-i("shelves of multigrain loaves", "杂粮面包货架")
+ #bi-i("inevitable indignity of being uninstalled and replace by ...\n", "被卸载并被……取代的不可避免的耻辱")
+ #bi-i("pose this skill can hit the big time", "掌握这项技能就能大获成功")
+ #bi-i("become more attached to the lifestyle", "变得更加依恋这种生活方式")
+ #bi-i("one kilometer in diameter", "直径一公里")
+ #bi-i("the feasibility of changing the direction of asteroids", "改变小行星方向的可行性")
+ #bi-i("It narrowly missed the earth.", "它与地球擦肩而过。")
+ #bi-i("be automating business decisions", "正在自动化商业决策")
+ #bi-i("a deep-learning algorithms", "深度学习算法")
+ #bi-i("reduced product returns", "减少产品退货")
+ #bi-i("establish", "发现,证实")
+ #bi-i("fit in with other research", "与其他研究相吻合")
+ #bi-i("in prospect", "在未来")
+ #bi-i("ready sb. to do", "使某人准备好去做某事")
+ #bi-i("a vast number of specialized experts", "大量的专业专家")
+ #bi-i("tap into that", "利用这一点")
+ #bi-i("What a choice there is!", "可供选择的东西真多！")
+ #bi-i("What a choice it is!", "这真是一个不错的选择！")
