+ #bi-i("It's better to be safe than sorry", "")
+ #bi-i("catch sb. off guard", "")
+ #bi-i("New Year's Day this year", "今年元旦")
+ #bi-i("congratulate me on my 18th birthday", "祝贺我18岁生日")
+ #bi-i("after years of constructi", "经过多年的建设")
+ #bi-i("one in his fifties", "五十多岁的人")
+ #bi-i("distinct spices", "已灭绝物种")
+ #bi-i("make up one's mind to join the wildlife conservation organization", "立志加入野生动物保护组织")
+ #bi-i("What life you will live in the future is up to you.", "将来过怎样的生活取决于你自己。")
+ #bi-i("turn many people into being crazy about shopping", "不少人变成购物狂")
+ #bi-i("vivid and bright colors", "鲜艳明亮的色彩")
+ #bi-i("What make the game unique is that ...", "这个游戏的独特之处在于")
+ #bi-i("have a comprehensive and accurate knowledge of your ability", "对你的能力有全面、准确的了解")
+ #bi-i("make it a practice to write thank-you notes", "")
+ #bi-i("a promising fix to mental distress", "")
+ #bi-i("in the face of what's cloudy, new or unexpected", "")
+ #bi-i("pathway to building toughness", "")
+ #bi-i("mismatch between what we assumed", "")
+ #bi-i("update our perception of the world", "")
+ #bi-i("originate the term", "")
+ #bi-i("blooms are a blooming bussiness", "")
+ #bi-i("an emerging market", "")
+ #bi-i("intensify the industry's environment footprint", "")
+ #bi-i("on top of pollutants and water use ", "")
+ #bi-i("generate serious carbon emissions", "")
+ #bi-i("be roughly equivalent to", "")
+ #bi-i("busy streets and towering high-rises", "")
+ #bi-i("decode local idioms", "")
+ #bi-i("convert A to B", "")
+ #bi-i("be carefully complied", "精心编写的")
+ #bi-i("fitness manual", "健身手册")
+ #bi-i("can't help marveling at sth.", "喷啧称奇")
+ #bi-i("tailor ... to specific needs", "对症下药")
+ #bi-i("presales are so popular that even a single ticket is unavailable", "预售火爆，一票难求")
+ #bi-i("unevenly distributed weight", "")
+ #bi-i("urban landscape", "")
+ #bi-i("fuel the imaginations of", "")
+ #bi-i("using ... of musicians can be exploitive", "")
+ #bi-i("scarcity of original video footage", "")
+ #bi-i("behave with integrity", "")
+ #bi-i("territorial integrity", "")
+ #bi-i("be loaded with many features", "")
+ #bi-i("optimism is justified", "")
+ #bi-i("donation from the public", "社会公众的捐赠")
+ #bi-i("gain recognitions", "受到认可")
+ #bi-i("things seemed good", "“听上去很美”的东西")
+ #bi-i("the association helps the young talents", "这个协会扶持青年才俊")
+ #bi-i("scientific exchange", "科学交流")

+ #bi-i("anthropologists", "")
+ #bi-i("proved controversial", "")
+ #bi-i("B be frequently owed to A", "")
+ #bi-i("in various literature forms", "")
+ #bi-i("shelves of multigrain loaves", "")
+ #bi-i("inevitable indignity of being uninstalled and replace by ...", "")
+ #bi-i("pose this skill can hit the big time", "")
+ #bi-i("become more attached to the lifestyle", "")
+ #bi-i("one kilometer in diameter", "")
+ #bi-i("the feasibility of changing the direction of asteroids", "")
+ #bi-i("It narrowly missed the earth.", "")
+ #bi-i("be automating business decisions", "")
+ #bi-i("a deep-learning algorithms", "")
+ #bi-i("reduced product returns", "")
+ #bi-i("establish", "发现,证实")
+ #bi-i("fit in with other research", "")
+ #bi-i("in prospect", "在未来")
+ #bi-i("a vast number of specialized experts", "")
+ #bi-i("tap into that", "")
+ #bi-i("What a choice there is!", "")
+ #bi-i("What a choice it is!", "")
