// 导入模板文件中的所有功能
#import "../template.typ": bi-i, setup, title-date

// 使用 #show 规则将 `setup` 函数应用到整个文档
#show: doc => setup(doc, 1)

// ================================================================
//                       下为正文内容
// ================================================================

// 1. 设置标题日期
#title-date("20251209")
#pad()[
  #h(1fr)
  #text(15pt, weight: "bold", fill: black)[ _Credits \@杨卓婷_ ]
]
// 2. 使用编号列表 (+) 和 bi-i 函数添加条目
+ #bi-i("be blessed with", "有幸享有；被赋予")
+ #bi-i("a measurable dip in starlight", "星光的可测量下降")
+ #bi-i("habitable zone of its star", "恒星的宜居带")
+ #bi-i("track small variations", "追踪微小的变化")
+ #bi-i("sensitive instruments and techniques", "灵敏的仪器和技术")
+ #bi-i("call for environment", "对环境的呼吁")
+ #bi-i("shift from teacher-centred education to ...\n", "从以教师为中心的教育转变为")
+ #bi-i("communicate the methods and the goals to the leaners\n", "向学习者传达方法和目标")
+ #bi-i("effort pays off", "努力得到回报")
+ #bi-i("in Chinese architectural", "在中国建筑风格中")
+ #bi-i("Don't litter.", "不要乱扔垃圾")
+ #bi-i("the all-new chatbot released on November 30, 2022\n", "2022年11月30日发布的全新聊天机器人")
+ #bi-i("simple and plain language", "语言平易浅近")
+ #bi-i("10-second timeout from", "从……暂停10秒")
+ #bi-i("credit A to B", "把A归功于B")
+ #bi-i("attend to", "照料；处理；致力于")
+ #bi-i("tune out", "不理睬；关掉；走神")
+ #bi-i("oversee the city’s transport system", "监管城市的交通系统")
+ #bi-i("We seek out and celebrate such shortcuts is ...", "我们寻找并推崇这样的捷径是")
+ #bi-i("our corresponding appetite for ease", "我们对安逸的相应渴望")
+ #bi-i("a necessary counterbalance to ...", "对……必要的平衡")
+ #bi-i("natural instinct to conserve energy", "保存能量的本能")
+ #bi-i("fashion technological world", "制造科技的世界")
+ #bi-i("about/of/on a wide range of topics from ...", "关于……的广泛话题")
+ #bi-i("advocacy for better elephant welfare", "倡导改善大象福利")
+ #bi-i("The debate around elephant tourism is deeply polarizing.\n", "关于大象旅游的辩论两极分化严重")
+ #bi-i("slightly outnumber the wild ones", "数量略多于野生大象")
+ #bi-i("That momentary relation between ...", "两者之间短暂的关系")
+ #bi-i("You all lean in to wonder at a rare find.", "你们都凑上前去惊叹这一罕见的发现")
+ #bi-i("a genetically de-formed clover", "不标准型的四叶草")
+ #bi-i("take over", "接管；接收")
+ #bi-i("give away", "赠送；泄露")
+ #bi-i("closeness", "亲密；接近")
+ #bi-i("embody understanding of what life might ideally be about\n", "体现了对理想生活意义的理解")
+ #bi-i("sophisticated knowledge of the behavior", "对行为的深刻了解")
+ #bi-i("map abstract concepts on ...", "将抽象概念映射到……")
+ #bi-i("be positively related with", "正相关")
+ #bi-i("estimated weight", "估计重量")
+ #bi-i("engage experts from", "聘请来自……的专家")
+ #bi-i("distinguish A from B", "区分A和B")
+ #bi-i("spot a gap in the market", "发现市场空白")
+ #bi-i("get a thorough understanding of ...", "彻底了解")
+ #bi-i("adopt a consistent approach", "采取一致的方法")
+ #bi-i("preparation clearly paid off", "准备工作显然有了回报")
+ #bi-i("acknowledge the inevitability of ego-centrism\n", "承认自我中心主义的不可避免性")
+ #bi-i("in later last year", "在去年晚些时候")
+ #bi-i("the information age", "信息时代")
+ #bi-i("mobile device", "移动设备")
+ #bi-i("by combining innovation with classic cuisine with culture\n", "通过将创新与经典美食及文化相结合")
+ #bi-i("Time-honored brands are revitalizing.", "老字号正在焕发新生")
+ #bi-i("As the models mature, ...", "随着模型的成熟")
+ #bi-i("turn us into passive consumers", "把我们变成了被动的消费者")
+ #bi-i("Companies are open to this consumer inattention.\n", "公司容易受到消费者这种注意力缺失的影响")
+ #bi-i("their access to consumers", "它们接触消费者的渠道")
+ #bi-i("be emotionally drained or needing time to recharge", "精疲力竭或需要时间充电")
+ #bi-i("The book has significant drawbacks.", "这本书有明显的缺点")
+ #bi-i("Fairy tales were never meant to be only sweet.\n", "童话故事从来就不应该只是甜蜜的")
+ #bi-i("worthy to be remembered", "值得被铭记")
+ #bi-i("bring a rare series of super-moons in a row", "带来一连串罕见的超级月亮")
+ #bi-i("the moon’s phase", "月相")
+ #bi-i("notable frequency", "显著的频率")
+ #bi-i("produce 3 super-moons successively", "连续产生3个超级月亮")
+ #bi-i("still", "仍然；静止")
+ #bi-i("becoming increasingly automatic through repetition", "通过重复变得越来越自动化")
+ #bi-i("driving instinctive action", "驱动本能行为")
+ #bi-i("the decision-making process", "决策过程")
+ #bi-i("go through", "经历；通过；检查")
+ #bi-i("score a major victory", "取得重大胜利")
+ #bi-i("over how ...", "关于如何")
+ #bi-i("be assumed that ...", "原本认为")
+ #bi-i("Findings are meant to generate awareness and underscore.\n", "研究结果旨在唤起意识并强调")
+ #bi-i("whenever it is rainy or windy", "每当刮风下雨时")
+ #bi-i("the Country Roads", "乡村道路")
+ #bi-i("round up with", "以……作为结束")
