+ #bi-i("hydrologist", "")
+ #bi-i("target and replenish", "")
+ #bi-i("pausing to let that visual sink in", "")
+ #bi-i("in effect", "")
+ #bi-i("deliberate fioods", "")
+ #bi-i("yields are affected", "")
+ #bi-i("pilot study", "")
+ #bi-i("comprehensive schools", "")
+ #bi-i("It takes several months to finish this project.", "完成这项任务要花好几个月的时间。(take)")
+ #bi-i("73. A concert was held in the park last weekend.", "上周末公园里举行了一场音乐会。(hold）")
+ #bi-i("74. Neither he nor his classmates  like to have extra lessons after school.", "他和他的同学都不喜欢放学后补课。(Neither…nor…)")
+ #bi-i("Many old people who live alone want their kids will visit them often.", "不少独居老人部希望自己的子女常回家看看。(who)")
+ #bi-i("The moment he stepped on the foreign land, Li Hua realized that it was extremely important to follow the local customs.", "从踏上陌生同土的那一刻起，李华就意识到入乡随俗至关重要。(the moment)")
