+ #bi-i("there is no proof that ...", "")
+ #bi-i("the proportion of A to B", "")
+ #bi-i("protest against", "")
+ #bi-i("This promotion proved to be a turning point in his career.", "")
+ #bi-i("promise to do", "")
+ #bi-i("provide sb. with sth.", "")
+ #bi-i("hold a charity sale", "")
+ #bi-i("for the purpose of", "")
+ #bi-i("sale for the purpose of ...", "")
+ #bi-i("raise money", "")
+ #bi-i("poverty stricken area", "")
+ #bi-i("on purpose", "")
+ #bi-i("serve the purpose of sth.", "")
+ #bi-i("push sb. into doing sth.", "")
+ #bi-i("put foward many questions", "")
+ #bi-i("be qualified for", "")
+ #bi-i("qualify you as a great teacher", "")
+ #bi-i("attitude towards the proposal is out of question", "")
+ #bi-i("at random", "")
+ #bi-i("range in length from A to B", "")
+ #bi-i("this species of rare animal", "")
+ #bi-i("at an alarming rate", "")
+ #bi-i("have no ready solution to refer to", "")
+ #bi-i("recommend sb. to do", "")
+ #bi-i("be in the habit of keeping a record of ...", "")
