+ #bi-i("abstract complex ideas from a flood of news and data", "")
+ #bi-i("absorb the core meaning", "")
+ #bi-i("accents exciting and shocking context", "")
+ #bi-i("adaptation of a classic novel", "")
+ #bi-i("acknowledge our own built-in biases", "")
+ #bi-i("accommodation to this chaotic information", "")
+ #bi-i("a passionate advocate", "")
+ #bi-i("a heart full of affection", "")
+ #bi-i("administrate the small library", "")
+ #bi-i("from a practical angle", "")
+ #bi-i("anticipate finding a perfect solution", "")
+ #bi-i("offer bare hope", "")
+ #bi-i("discovery be attainable", "")
+ #bi-i("dedication be awesomely dear", "")
+ #bi-i("appetite for innovative public art", "")
+ #bi-i("appreciate how Ms.Chen's vision", "")
+ #bi-i("debate over", "")
+ #bi-i("bitter", "")
+ #bi-i("mind go blank", "")
+ #bi-i("the strong social bond", "")
+ #bi-i("boost investment in", "")
+ #bi-i("bounce between recovery and stagnation.", "")
+ #bi-i("be bound to face legal challenges", "")
+ #bi-i("a bunch of concerned citizens", "")
+ #bi-i("the strongest candidate for the new technology park", "")
+ #bi-i("be filled to capacity", "")
