+ #bi-i("feed by adults nostalgic for simpler times", "")
+ #bi-i("going to great lengths to do", "")
+ #bi-i("A full collection commands more than $700", "")
+ #bi-i("overturn our common sense", "")
+ #bi-i("restock time", "")
+ #bi-i("conquer the final frontier", "")
+ #bi-i("squeeze time for me", "")
+ #bi-i("pick a cause", "")
+ #bi-i("be alert collaborators", "")
+ #bi-i("incorporation of realistic details", "")
+ #bi-i("add new wrinkles to the controversy", "")
+ #bi-i("depend on their customer's mercy", "")
+ #bi-i("can't help to saying in amazement", "不禁感叹")
+ #bi-i("places worth visiting", "值得看的地方")
+ #bi-i("the element of calligraphy", "书法这一元素")
+ #bi-i("Peking Opera costumes", "京剧戏服")
+ #bi-i("mix into a limited place", "融汇在一个特定的空间里")
+ #bi-i("specifically tailored paper ruler", "")
+ #bi-i("proceed through the game", "")
+ #bi-i("be in a rush to do", "")
+ #bi-i("as it happens", "")
+ #bi-i("the unexpected", "")
+ #bi-i("integrate into our lives", "")
+ #bi-i("grasp", "理解")
+ #bi-i("reproduce these capabilities", "")
+ #bi-i("understand the motivations behind actions", "")
+ #bi-i("route sb. to sth.", "")
+ #bi-i("clues encode in ancient objects and rare books", "")
+ #bi-i("spark the author's passion for", "")
+ #bi-i("shipping containers", "")
+ #bi-i("unlock their low-cost and sustainable development potential", "")
+ #bi-i("exchange of rights and mutual support", "")
+ #bi-i("the earth orbits around the sun", "地球绕太阳公转")
+ #bi-i("the length variation of day and night", "昼夜长短的变化")
+ #bi-i("celebration ceremony", "庆典")
+ #bi-i("represent a tendency to do", "呈现出")
+ #bi-i("it is worth doing", "")
+ #bi-i("entertainment experiences associated with cities' landmarks", "与城市地标相关的特色娱乐体验")
+ #bi-i("actually a misrepresentation of what most hackers do", "")
+ #bi-i("plug the security holes", "")
+ #bi-i("here's the catch", "这里有个问题")
+ #bi-i("Still,", "尽管，")
+ #bi-i("intervene, if they appear distracted or tired", "")
+ #bi-i("finding calm in chaos", "")
+ #bi-i("quick fixes for happiness", "")
+ #bi-i("resolve the easiest puzzle", "")
+ #bi-i("straightforward approach", "")
+ #bi-i("in the distance", "")
+ #bi-i("at a distance", "")
+ #bi-i(".... that", "未知")
+ #bi-i("streamline its operations to focus on profitability", "")
+ #bi-i("activate hard-wired behaviors", "")
+ #bi-i("be down to", "归因于")
+ #bi-i("at intervals", "每隔一段")
+ #bi-i("be caught on globally", "全球围内流行起来")
+ #bi-i("works be highly praised in one's youth", "年轻时的作品曾备受推崇")
+ #bi-i("influential", "轰动")
+ #bi-i("discuss ethics and philosophy", "")
+ #bi-i("reaction and revision", "")
+ #bi-i("predate their own lives", "")
+ #bi-i("unproductive obsession with an idealized past", "")
+ #bi-i("thrive", "繁荣，茁壮成长")
+ #bi-i("reveal the future", "")
+ #bi-i("supervised playtime", "")
+ #bi-i("be wired to do", "")
+ #bi-i("a control participant", "对照组")
+ #bi-i("Do not leave the children unattended near the swimming pool, do you?", "别让孩子们在游泳池边没人看管，好吗？")
+ #bi-i("integrate forms and spirits", "形神兼备")
+ #bi-i("newly-married couples", "新婚夫妻")
+ #bi-i("villa", "别墅")
+ #bi-i("be a great drain to their savings", "消耗了他们的积蓄")
+ #bi-i("no shortcut to success", "成功没有捷径")
+ #bi-i("establish oneself in sp.", "有所建树")
+ #bi-i("down to earth", "脚踏实地")
