+ #bi-i("make an emergency supplies kit", "")
+ #bi-i("concern is growing over the role of fast food", "")
+ #bi-i("assemble the meal", "")
+ #bi-i("specify what they want", "")
+ #bi-i("a side dish", "")
+ #bi-i("solution to ensuring a healthier generation and providing consumer choice", "")
+ #bi-i("all told", "")
+ #bi-i("have locations nationwide", "")
+ #bi-i("a huge publicity success", "")
+ #bi-i("be exceptional in the amount of attention it grabbed", "")
+ #bi-i("The updated version of the original, famed for its seemingly indestructible qualities.", "")
+ #bi-i("news of its release leaked", "")
+ #bi-i("appear to have lost none of the charm and identity of the original", "")
+ #bi-i("the phone has a slightly bigger screen ha its namesake", "")
+ #bi-i("merely a marketing exercise", "")
+ #bi-i("feature phones", "")
+ #bi-i("a retro feature phone that shipped 17 years ago", "")
+ #bi-i("be bound to", "")
+ #bi-i("a cutting edge technology", "")
+ #bi-i("The team is committed to delivering high-quality results on time.", "")
+ #bi-i("cheer for sb. to do", "")
+ #bi-i("bring fresh ideas throughout her writing", "")
+ #bi-i("She started to play the violin five years ago.", "她五年前开始拉小提琴。(play)")
+ #bi-i("The flight was delayed for several hours owing to the terrible weather.", "由于天气恶劣航班延误了好几个小时。(owing)")
+ #bi-i("Every designer hope that their works can stand the challenges of time", "每位设计师都希望自己的作品能经受时间的考验。(stand)")
+ #bi-i("It is a tough problem for the middle school students whether they can resist the temptation of online game", "能否抵御网络游戏的诱惑是摆在中学生面前的一道难题。(It)")
+ #bi-i("At the exhibition，the company's sales manager demonstrated the new type of electronic toys that children were looking forward to.", "在展览会上,公司销售经理展示了孩子们翘首以盼的新型电子玩具。(demonstrate)")
