+ #bi-i("keep a secret from sb.", "")
+ #bi-i("be secured from", "")
+ #bi-i("see to it that", "")
+ #bi-i("make sure that", "")
+ #bi-i("seem to have done", "")
+ #bi-i("sth. sell well", "")
+ #bi-i("sth. be sold out", "")
+ #bi-i("be senior to", "")
+ #bi-i("make any sense", "")
+ #bi-i("make sense of sth.", "")
+ #bi-i("it is sensible of sb. to do", "")
+ #bi-i("be sensitive to", "")
+ #bi-i("be sentenced to", "")
+ #bi-i("take sth. too seriously", "")
+ #bi-i("serve the purpose", "")
+ #bi-i("set about doing", "")
+ #bi-i("sets aside do", "")
+ #bi-i("set out to do", "")
+ #bi-i("settle down", "")
+ #bi-i("settle down an argument", "")
+ #bi-i("what a shame", "")
+ #bi-i("be deeply shaped by", "")
+ #bi-i("take shelters from", "")
+ #bi-i("shift A to B", "")
+ #bi-i("be short of", "")
+ #bi-i("shortly after", "")
+ #bi-i("shoulder the responsibility of", "")
+ #bi-i("arise-arose-arisen", "arise-过去式-过去分词")
+ #bi-i("awake-awoke-awaken", "awake")
+ #bi-i("bear-bore-born", "bear")
+ #bi-i("beat-beat-beaten", "beat")
+ #bi-i("bind-bound-bound", "bind")
+ #bi-i("bite-bite-bitten", "bite")
+ #bi-i("bleed-bled-bled", "bleed")
+ #bi-i("breed-bred-bred", "breed")
+ #bi-i("drive-drove-driven", "drive")
+ #bi-i("fall-fell-fallen", "fall")
+ #bi-i("fly-flew-flown", "fly")
+ #bi-i("hang-hanged-hanged", "hang(绞死)")
+ #bi-i("hang-hung-hung", "hang（悬挂；闲逛）")
+ #bi-i("knit-knit/knitted-knit/knitted", "knit")
+ #bi-i("lay-laid-laid", "lay")
+ #bi-i("lend-lent-lent", "lend")
+ #bi-i("lie-lied-lied", "lie(说谎）")
+ #bi-i("lie-lay-lain", "lie(躺下；放置；坐落；在于)")
+ #bi-i("light-lit-lit", "light(照亮）")
+ #bi-i("light-lit-[表语]lit/[定语]lighted", "light(（点燃）")
