+ #bi-i("feel dizzy", "")
+ #bi-i("not jump to conclusion", "")
+ #bi-i("a housewarming party", "")
+ #bi-i("get sb. in top shape", "")
+ #bi-i("under the weather lately", "")
+ #bi-i("get back on the track", "")
+ #bi-i("a mental construct created by our brain's interpretation of these vibrations", "")
+ #bi-i("acknowledge the limitations of our hearing", "")
+ #bi-i("interplay between sound waves and process capabilities", "")
+ #bi-i("interval", "")
+ #bi-i("intensity", "")
+ #bi-i("embark on a mission to do", "")
+ #bi-i("who is gravely ill", "")
+ #bi-i("relay one's message", "")
+ #bi-i("compressed matter in space", "")
+ #bi-i("far-fetched", "")
+ #bi-i("indifferent late people", "")
+ #bi-i("relativity", "")
+ #bi-i("days are numbered", "")
+ #bi-i("infinite density and pressure", "")
+ #bi-i("discount other possibilities", "")
