+ #bi-i("Success has no simple recipe.", "")
+ #bi-i("relay live on the local radio station", "")
+ #bi-i("support the local bird reserve", "")
+ #bi-i("the time was ripe for decisive action", "")
+ #bi-i("proposed change too rigid", "")
+ #bi-i("address the root cause", "")
+ #bi-i("created a challenging riddle", "")
+ #bi-i("focused on their respective teams' strengths", "")
+ #bi-i("secure the site from any potential damage", "")
+ #bi-i("on the edge of becoming a ruin", "")
+ #bi-i("shade him from the afternoon sun", "")
+ #bi-i("shadow a person of interest", "")
+ #bi-i("seek shelter from a sudden downpour", "")
+ #bi-i("truth began to sink in", "")
+ #bi-i("found a critical slip in his earlier assumptions", "")
+ #bi-i("spot a subtle improvement in", "")
+ #bi-i("the long stretch of parkland", "")
+ #bi-i("cluttered research process", "")
+ #bi-i("string of key experiments", "")
+ #bi-i("superior remained suspicious of the data", "")
+ #bi-i("subscribe to her argument", "")
+ #bi-i("submit to his demand for revision", "")
+ #bi-i("subsequent change", "")
+ #bi-i("sweep across the region businesses", "")
+ #bi-i("tank", "")
+ #bi-i("swing from initial optimism to anxiety", "")
+ #bi-i("suspend a series of ambitious infrastructure projects", "")
+ #bi-i("sustained effort", "")
+ #bi-i("weather the storm", "")
+ #bi-i("disputed territory", "")
+ #bi-i("trap nations into a cycle of conflict", "")
+ #bi-i("tolerate provocation", "")
+ #bi-i("trick them with false promise", "")
+ #bi-i("tune the differing national policies", "")
+ #bi-i("a vital vision for change", "")
+ #bi-i("increasing the volume of public participation", "")
+ #bi-i("latest version of action plan", "")
+ #bi-i("virtue of collective responsibility", "")
+ #bi-i("long-term vision recognized ...", "")
+ #bi-i("wrestle with a deep sense of loss", "")
+ #bi-i("be wired with patience", "")
+ #bi-i("emotional welfare", "")
+ #bi-i("add a wrinkle to their plan", "")
