+ #bi-i("this idea strike you", "")
+ #bi-i("The company goes on strike.", "")
+ #bi-i("striving for peace", "")
+ #bi-i("struggle with cancer", "")
+ #bi-i("be subject to the following rules", "")
+ #bi-i("substitute A for B", "")
+ #bi-i("succeed in doing", "")
+ #bi-i("all of a sudden", "")
+ #bi-i("suffer huge losses", "")
+ #bi-i("A be superior to B", "")
+ #bi-i("was/were supposed to do", "")
+ #bi-i("suspect sb. sth.", "")
+ #bi-i("tailor sth. to sb.", "")
+ #bi-i("take one's temperature", "")
+ #bi-i("career takes off", "")
+ #bi-i("the opposing side takes over", "")
+ #bi-i("have a talent for", "")
+ #bi-i("be targeted to", "")
+ #bi-i("burst into tears", "")
+ #bi-i("be live televised", "")
+ #bi-i("tell sth. apart", "")
+ #bi-i("It is no use losing temper.", "")
+ #bi-i("tempt sb. to sth.", "")
+ #bi-i("tend to the injured man", "")
+ #bi-i("The clock struck midnight.", "")
