+ #bi-i("have a tendency to do", "")
+ #bi-i("tremble with terror", "")
+ #bi-i("be thirsty for knowledge", "")
+ #bi-i("This species is threatened with extinction.", "")
+ #bi-i("threatened to do", "")
+ #bi-i("It is the first time that sb. have topped list", "")
+ #bi-i("on a tour of", "")
+ #bi-i("be traced back to", "")
+ #bi-i("keep track of", "")
+ #bi-i("trade A for B", "")
+ #bi-i("be transferred to", "")
+ #bi-i("treat sb. with great care", "")
+ #bi-i("treat sth, as ...", "")
+ #bi-i("treat sb. a movie", "")
+ #bi-i("play tricks on sb.", "")
+ #bi-i("turn down my request", "")
+ #bi-i("turn out to be a lie", "")
+ #bi-i("take over sth, to sb,", "")
+ #bi-i("turn over a new leaf", "")
+ #bi-i("turn up at sp.", "")
+ #bi-i("be a typical story of", "")
+ #bi-i("undergo both physical and psychological changes", "")
+ #bi-i("I won't attack others unless others attacks me.", "")
+ #bi-i("He didn't begin to play piano until she was fifteen.", "")
+ #bi-i("urge sb. not to do sth.", "")
+ #bi-i("be in urgent need of", "")
