+ #bi-i("ento the picture", "")
+ #bi-i("keep/hold sth. in place", "")
+ #bi-i("set aside a whole year", "")
+ #bi-i("nothing more pleasure than", "")
+ #bi-i("be pleasing to the eye", "")
+ #bi-i("plunged into discussion", "")
+ #bi-i("There's no point arguing over sth.", "")
+ #bi-i("be in no position to do", "")
+ #bi-i("postpone doing", "")
+ #bi-i("sing one's praises", "")
+ #bi-i("prepare for sth.", "")
+ #bi-i("in the presence of teenagers", "")
+ #bi-i("be present at the ceremony", "")
+ #bi-i("present sth. to sb.", "")
+ #bi-i("pretend to have a sound sleep", "")
+ #bi-i("take pride in doing", "")
+ #bi-i("be the top priority", "")
+ #bi-i("in the process of doing", "")
+ #bi-i("B profit from A.", "")
+ #bi-i("research on animals abilities", "")
+ #bi-i("under the age of 18", "")
+ #bi-i("prohibit sb. from doing", "")
+ #bi-i("A timely snow promises a good harvest", "瑞雪兆丰年")
