+ #bi-i("signal to sb. that", "这里填写中文翻译")
+ #bi-i("in a situation where", "")
+ #bi-i("find a solution to", "")
+ #bi-i("sort out", "")
+ #bi-i("in high spirits", "")
+ #bi-i("in spite of fog", "")
+ #bi-i("split the bill", "")
+ #bi-i("spoil our holiday", "")
+ #bi-i("spot the problem", "")
+ #bi-i("spread the cloth on the table", "")
+ #bi-i("spy on sb.", "")
+ #bi-i("freshly-squeezed orange juice", "")
+ #bi-i("live up to the required standard", "")
+ #bi-i("be starved to death", "")
+ #bi-i("stay open until midnight", "")
+ #bi-i("taking step to prevent", "")
+ #bi-i("stick to", "")
+ #bi-i("be stock with", "")
+ #bi-i("out of stock", "")
+ #bi-i("stop sb. from doing", "")
+ #bi-i("report stressed that", "")
+ #bi-i("stretch for hundreds of meters", "")
