+ #bi-i("release in several languages for", "")
+ #bi-i("The name is similar to those of her two brothers", "")
+ #bi-i("... has brought since it became popular online", "")
+ #bi-i("breeding programs for ...", "")
+ #bi-i("dependence on willpower", "")
+ #bi-i("restriction of personal freedom", "")
+ #bi-i("cultivate true freedom", "")
+ #bi-i("the 'master talent' underlying emotional intelligence", "")
+ #bi-i("wind up doing better", "")
+ #bi-i("underwent psychological assessment at various ages", "")
+ #bi-i("look at self-reported levels of", "")
+ #bi-i("cause tension in the relationship", "")
+ #bi-i("health problems associated with aging", "")
+ #bi-i("clinical diagnosis", "")
+ #bi-i("abuse understanding of theories", "")
+ #bi-i("trapped within the framework of ...", "")
+ #bi-i("souvenirs with local characteristics", "有当地特色的纪念品")
+ #bi-i("the freedom of spend their time", "自由支配时间")
+ #bi-i("choose flexible employment", "选择灵活就业")
+ #bi-i("rely too much on Artificial Intelligence", "过度依赖人工智能")
+ #bi-i("make good use of tools", "善用其作为工具")
+ #bi-i("defend against the approaching typhoon", "抵御台风来袭")
+ #bi-i("regardless of the wind and rain", "正项风冒雨")
+ #bi-i("going door to door to do", "挨家挨户去做某事")
+ #bi-i("move the potted plants indoors", "把盆栽搬入室内")
