+ #bi-i("take the view that ...", "这里填写中文翻译")
+ #bi-i("vote against the proposal", "")
+ #bi-i("warn us against thieves", "")
+ #bi-i("warn him of the danger of going out alone", "")
+ #bi-i("It's a waste of time watching this film.", "")
+ #bi-i("She left before I had time to wave goodbye to her.", "")
+ #bi-i("weight the advantages of this plan against the risks", "")
+ #bi-i("be wild with joy", "")
+ #bi-i("wind your watch.", "")
+ #bi-i("witness to the accident", "")
+ #bi-i("The 1990s witnessed the rapid development of China's economy.", "")
+ #bi-i("I can't help wondering at the beautiful scenery.", "")
+ #bi-i("Word comes that ...", "")
+ #bi-i("have a large collection of works of art", "")
+ #bi-i("one's worried expression", "")
+ #bi-i("be worth reading again and  again", "")
+ #bi-i("get a 50 dollars' worth books", "")
+ #bi-i("be worthy of being considered", "")
